### ISSUE TITLE
Additional Features

### ISSUE THREAD

**Issue by dWoolridge** [Wanztwurst/MMM-portscan#1]
Sorry that I'm very new to GitHub, so I don't know the best way to offer some features that I've added to your MMM-portscan.  I prefer not to add a fork to create another module to look through, so here's a summary and attached modified code.  I'm hoping that you'd like to incorporate it into your version.  See the attached picture for how it looks.  The attached "txt" file is the modified MMM-portscan.js

**Added to the main config:**
  portalign:  (in addition to text align) -- allows the port info to be aligned differently than the host
  portfontsize:  allows the port text font to be smaller (or larger) than the host

**Added to each ports:  definition**
  upText:  Replaces the port (or displayedName) text with the upText if the port is open
  downText:  Replaces the port (or displayedName) text with the downText if the port is closed

Example config.js:
```
{
module: 'MMM-portscan',
  position: 'bottom_right',
  header: 'Network Status',
  config: {
                 updateInterval: 60,      // in seconds
                 textalign: 'left',       // left, right, center
                 portalign: 'right',      // left, right, center
                 portfontsize: '15px',    // font size for ports
                 color_open: '#00ff00',   // hex value or empty
                 color_closed: '#ff0000', // hex value or empty
                 hosts: [
                             {
                                hostname: '192.168.0.5',
                                displayedName: 'Automator',
                                ports: [
                                             {port: 80, displayedName: 'Apache'},
                                             {port: 8080, displayedName: 'HomeSeer'},
                                             {port: 1883, displayedName: 'MQQT'}
                                ]
                              },
                              {
                                hostname: '192.168.0.12',
                                displayedName: 'Epson ET-3760',
                                ports: [
                                             {port: 80, upText: 'Up', downText: 'DOWN'},
                                ]
                              },
                 ]
               }
}
```

![MMM-portscan_modified](https://user-images.githubusercontent.com/16481972/192163760-7fafdc0f-c826-4905-9c97-51d673f90947.png)
[MMM-portscan.js.txt](https://github.com/Wanztwurst/MMM-portscan/files/9641721/MMM-portscan.js.txt)

**Comment by Wanztwurst** [comment]
Hello dWoolridge,

the right way to add features is to open pull requests. Issues are used to propose changes or open a discussion about something. 

But I don't want to change anything here, since I'm not using MagicMirror myself. Please go ahead and create a fork if you want to publish your version.
